export const ACTIVITY_RESULT_LOADING = "ACTIVITY_RESULT_LOADING"
export const ACTIVITY_RESULT_ERROR = "ACTIVITY_RESULT_ERROR"
export const ACTIVITY_RESULT_SUCCESS = "ACTIVITY_RESULT_SUCCESS"
export const CLEAR_ACTIVITY_RESULT = "CLEAR_ACTIVITY_RESULT"
